const cardList = `
[
    {		"id": 1,
        "img": "./img/31.jpg",
        "title": "ELLERY X M'O CAPSULE",
        "text": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "$52",
				"color": "Red",
				"size": "XL",
				"quantity": 2
    },
    {		"id": 2,
        "img": "./img/Image.png",
        "title": "ELLERY X M'O CAPSULE",
        "text": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "$52",
				"color": "Red",
				"size": "XL",
				"quantity": 2
    },
    {		"id": 3,
        "img": "./img/33.png",
        "title": "ELLERY X M'O CAPSULE",
        "text": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "$52",
				"color": "Red",
				"size": "XL",
				"quantity": 2
    },
    {		"id": 4,
        "img": "./img/34.png",
        "title": "ELLERY X M'O CAPSULE",
        "text": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "$52",
				"color": "Red",
				"size": "XL",
				"quantity": 2
    },
    {		"id": 5,
        "img": "./img/35.png",
        "title": "ELLERY X M'O CAPSULE",
        "text": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "$52",
				"color": "Red",
				"size": "XL",
				"quantity": 2
    },
    {		"id": 6,
        "img": "./img/36.png",
        "title": "ELLERY X M'O CAPSULE",
        "text": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "$52",
				"color": "Red",
		"size": "XL",
		"quantity": 2
    }
]`;
